# Generated by Django 5.2 on 2025-04-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
                ('level', models.CharField(max_length=10)),
                ('room', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('btvn', 'BTVN'), ('ktt', 'Kiểm tra')], max_length=10)),
                ('link', models.URLField(blank=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_name', models.CharField(max_length=50)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(blank=True, max_length=100)),
                ('parent_phone', models.CharField(blank=True, max_length=20)),
                ('student_phone', models.CharField(blank=True, max_length=20)),
                ('face_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.class')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('on_time', 'Đúng giờ'), ('late', 'Đi muộn'), ('absent', 'Vắng')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=10)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('ktt_score', models.FloatField(blank=True, null=True)),
                ('voucher_score', models.FloatField(blank=True, null=True)),
                ('diligence_score', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TuitionRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=1000000)),
                ('proof_url', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('confirmed', 'Đã duyệt')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
    ]
