# Generated by Django 5.2 on 2025-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_schedule_slot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionrecord',
            name='proof_url',
        ),
        migrations.AddField(
            model_name='tuitionrecord',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='tuition_proofs/'),
        ),
    ]
