# Generated by Django 5.2 on 2025-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_tuitionrecord_proof_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionrecord',
            name='proof_image',
        ),
        migrations.AddField(
            model_name='student',
            name='face_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuitionrecord',
            name='proof_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
