# Generated by Django 5.2 on 2025-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_tuitionrecord_proof_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionrecord',
            name='proof_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
